# Problem 2 @ projecteuler.net
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

r1 = 1
r2 = 1
count = 0

for i in 0..500
  r1 = r1 + r2
  if r1 > 4000000
    # puts r1
    break
  end
  if r1%2 == 0
    count += r1
  end
      
  r2 = r2 + r1
  if r2 > 4000000
    # puts r2
    break
  end
  if r2%2 == 0
    count += r2
  end
end

puts count